version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq-container'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network

  order:
    image: zakyfatih/order-service:latest
    container_name: 'order-service'
    ports:
      - 3000:3000
    volumes:
      - .:/src
    depends_on:
      - "rabbitmq"
    environment:
      - PORT=3000
      - AMQP_URL="amqp://localhost:5672"
    networks:
      - rabbitmq_network

  shipping:
    image: zakyfatih/shipping-service:latest
    container_name: 'shipping-service'
    ports:
      - 3001:3001
    volumes:
      - .:/src
    depends_on:
      - "rabbitmq"
    environment:
      - PORT=3001
      - AMQP_URL="amqp://localhost:5672"
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
