# Menentukan versi docker-compose yang digunakan, yaitu 3.7
version: "3.7"

# Mendefinisikan service yang akan dibuat
services:

  # Mendefinisikan service ke-1 yaitu item-app
  item-app:
    
    # Mendefinisikan nama container
    container_name: item-app

    # item-app akan memakai image container bernama item-app dengan tag:v1
    image: zakyfatih/submission-1:v1

    # Mengekspos ke port:80 ke host dan port:8080 ke container
    ports:
      - 80:8080

    # Memastikan bahwa item-app hanya berjalan setelah item-db diluncurkan
    depends_on:
      - item-db

    # Mendefiniskan restart policy yang jika container gagal berjalan, akan dilakukan restart otomatis
    restart: on-failure

  # Mendefinisikan service ke-2 yaitu item-db
  item-db:

    # Mendefinisikan nama container
    container_name: item_db

    # Menggunakan image mongo:3
    image: mongo:3

    # 
    ports:
      - 27017:27017

    # Memakai volume bernama app-db dengan target /data/db
    volumes:
      - app-db:/data/db

    # Mendefiniskan restart policy yang jika container gagal berjalan, akan dilakukan restart otomatis
    restart: on-failure

# Membuat satu buah volume bernama app-db
volumes:

  app-db:
    name: app-db