# Membuat secret env untuk mongodb
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: submission-2
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==